name: Send Random Hadith

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  HADITH_DISCORD_WEBHOOK_URL: ${{ secrets.HADITH_DISCORD_WEBHOOK_URL }}

jobs:
  send-hadith:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch hadith and send to Discord
        shell: bash
        run: |
          set -euo pipefail

          collections=("abu-dawud" "ahmad" "bukhari" "darimi" "ibnu-majah" "malik" "muslim" "nasai" "tirmidzi")
          collection=${collections[$RANDOM % ${#collections[@]}]}

          collection_response=$(curl -s "https://api.hadith.gading.dev/${collection}")
          
          total_hadiths=$(echo "$collection_response" | jq -r '.total')
          
          if [ "$total_hadiths" = "null" ] || [ -z "$total_hadiths" ]; then
            echo "Could not get total hadith count"
            exit 1
          fi

          random_number=$((RANDOM % total_hadiths + 1))

          hadith_response=$(curl -s "https://api.hadith.gading.dev/${collection}/${random_number}")

          hadith_arabic=$(echo "$hadith_response" | jq -r '.data.contents.arab')
          hadith_english=$(echo "$hadith_response" | jq -r '.data.contents.id // ""')
          book_name=$(echo "$hadith_response" | jq -r '.data.name')
          hadith_number=$(echo "$hadith_response" | jq -r '.data.number')

          if [ -z "$hadith_arabic" ] || [ "$hadith_arabic" = "null" ]; then
            echo "Could not extract hadith text, raw response:"
            echo "$hadith_response"
            exit 1
          fi

          arabic_payload=$(jq -n \
            --arg hadith "$hadith_arabic" \
            --arg book "$book_name" \
            --arg num "$hadith_number" \
            '{
              embeds: [
                {
                  description: $hadith,
                  color: 5763719,
                  footer: {
                    text: ($book + " - حديث " + $num)
                  }
                }
              ]
            }')

          curl --fail -X POST "$HADITH_DISCORD_WEBHOOK_URL" \
               -F "payload_json=$arabic_payload"

          if [ -n "$hadith_english" ] && [ "$hadith_english" != "null" ] && [ "$hadith_english" != "" ]; then
            english_payload=$(jq -n \
              --arg english "$hadith_english" \
              --arg book "$book_name" \
              --arg num "$hadith_number" \
              '{
                embeds: [
                  {
                    description: $english,
                    color: 5763719,
                    footer: {
                      text: ($book + " - Hadith " + $num)
                    }
                  }
                ]
              }')

            curl --fail -X POST "$HADITH_DISCORD_WEBHOOK_URL" \
                 -H "Content-Type: application/json" \
                 -d "$english_payload"
          fi
