name: Send Random Hadith

on:
  schedule:
    # Runs every hour at the start of the hour
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  send-hadith:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Hadith, build embed and send
        shell: bash
        run: |
          set -euo pipefail

          # Fetch a single random hadith from the API
          hadith_json=$(curl -s "https://sunnah.com/api/hadiths/random")

          # --- Parse JSON for Arabic & English details ---
          # Note: The API returns an array for 'hadith'. [0] is Arabic, [1] is English.
          hadith_ar_text=$(echo "$hadith_json" | jq -r '.hadith[0].body')
          hadith_en_text=$(echo "$hadith_json" | jq -r '.hadith[1].body')

          collection_slug=$(echo "$hadith_json"| jq -r '.collection')
          collection_ar=$(echo "$hadith_json" | jq -r '.collectionInfo.arabic_title')
          collection_en=$(echo "$hadith_json" | jq -r '.collectionInfo.english_title')

          book_num=$(echo "$hadith_json" | jq -r '.hadith[0].bookNumber')
          hadith_num=$(echo "$hadith_json" | jq -r '.hadith[0].hadithNumber')

          chapter_title_ar=$(echo "$hadith_json" | jq -r '.hadith[0].chapterTitle')
          chapter_title_en=$(echo "$hadith_json" | jq -r '.hadith[1].chapterTitle')

          # Construct a direct link to the hadith on sunnah.com
          hadith_url="https://sunnah.com/${collection_slug}/${hadith_num}"

          # --- Parse Grading Information ---
          # Uses jq's "alternative operator" `//` to prevent errors if grades are missing.
          grade_ar_name=$(echo "$hadith_json" | jq -r '.hadith[0].grades[0].graded_by // "غير محدد"')
          grade_ar_grade=$(echo "$hadith_json"| jq -r '.hadith[0].grades[0].grade // "N/A"')
          grade_en=$(echo "$hadith_json" | jq -r '.hadith[1].grades[0].grade // "Not Available"')

          # --- Build and Send Arabic Embed ---
          arabic_payload=$(jq -n \
            --arg hadith_ar "$hadith_ar_text" \
            --arg chapter_ar "$chapter_title_ar" \
            --arg collection_ar "$collection_ar" \
            --arg book_num "$book_num" \
            --arg hadith_num "$hadith_num" \
            --arg grade_name "$grade_ar_name" \
            --arg grade_val "$grade_ar_grade" \
            --arg url "$hadith_url" \
            '{
              "embeds": [
                {
                  "title": ($collection_ar + " - الحديث رقم " + $hadith_num),
                  "url": $url,
                  "description": ("**الباب**: " + $chapter_ar + "\n\n" + $hadith_ar),
                  "color": 3066993,
                  "fields": [
                    {
                      "name": "الدرجة",
                      "value": ($grade_name + ": **" + $grade_val + "**"),
                      "inline": true
                    }
                  ],
                  "footer": {
                    "text": ("الكتاب " + $book_num)
                  }
                }
              ]
            }')

          curl --fail -X POST "$DISCORD_WEBHOOK_URL" \
               -H "Content-Type: application/json" \
               -d "$arabic_payload"

          # --- Build and Send English Embed (as a separate message) ---
          english_payload=$(jq -n \
            --arg hadith_en "$hadith_en_text" \
            --arg chapter_en "$chapter_title_en" \
            --arg collection_en "$collection_en" \
            --arg book_num "$book_num" \
            --arg hadith_num "$hadith_num" \
            --arg grade "$grade_en" \
            --arg url "$hadith_url" \
            '{
              "embeds": [
                {
                  "title": ($collection_en + " - Hadith " + $hadith_num),
                  "url": $url,
                  "description": ("**Chapter**: " + $chapter_en + "\n\n" + $hadith_en),
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Grade",
                      "value": "**" + $grade + "**",
                      "inline": true
                    }
                  ],
                  "footer": {
                    "text": ("Book " + $book_num)
                  }
                }
              ]
            }')

          curl --fail -X POST "$DISCORD_WEBHOOK_URL" \
               -H "Content-Type: application/json" \
               -d "$english_payload"
